service: nuxt-sandbox
frameworkVersion: '3'
provider:
  name: aws
  stage: dev
  region: ap-northeast-1
  runtime: nodejs20.x
package:
  patterns:
    - '!**'
    - '.output/**' 
functions:
  NuxtSsrEngine:
    handler: '.output/server/index.handler'
    url: true